version: '3'
services:
  python3_sub:
    image: paho-python3
    container_name: 'python3_sub'
    # working_dir: '/root/'
    tty: true
    # volumes:
    #   - ./opt:/root/opt
  python3_pub:
    image: paho-python3
    container_name: 'python3_pub'
    # working_dir: '/root/'
    tty: true
    # volumes:
    #   - ./opt:/root/opt
  artemis:
    image: artemis-centos
    container_name: 'artemis'
    ports:
      - 61616:61616
      - 8161:8161